FileVersion = 1
Dependencies = {corlib = "*", ari_io = "*"}

[Project]
Name = "ari_gfx"
TargetType = "BeefLib"
StartupObject = "ari_gfx.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/../dist/win64/Debug/cari_gfx.lib", "$(ProjectDir)/../dist/win64/Debug/ari_gfx.lib", "$(ProjectDir)/../dist/win64/Debug/glfw3.lib", "opengl32.lib", "gdi32.lib", "shell32.lib", "User32.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/../dist/win64/Release/cari_gfx.lib", "$(ProjectDir)/../dist/win64/Release/ari_gfx.lib", "$(ProjectDir)/../dist/win64/Release/glfw3.lib", "opengl32.lib", "gdi32.lib", "shell32.lib", "User32.lib"]
